services:
  goai:
    image: tabortoa/goai #国内用户镜像加速 dk.nastool.de/tabortoa/goai
    restart: always
    ports:
      - "1388:8080"
    command: ["server"]
    volumes:
      - ./config.json:/root/config.json 
    #   - ollama

  # ollama:
  #   image: ollama/ollama
  #   ports: 
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   container_name: ollama 

# volumes:
#   ollama_data: 