# .github/workflows/release.yml

name: Release Go Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: '发布版本标签 (例如: v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Determine Release Tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          fi

      - name: Set output executable name
        id: set_name
        run: |
          # Clean the release tag using shell string replacement
          RELEASE_TAG_CLEAN=$(echo "${{ env.RELEASE_TAG }}" | sed 's/\//-/g')
          if [ "${{ matrix.goos }}" == "windows" ]; then
            echo "exe_name=goai-${{ matrix.goos }}-${RELEASE_TAG_CLEAN}.exe" >> $GITHUB_ENV
          else
            echo "exe_name=goai-${{ matrix.goos }}-${RELEASE_TAG_CLEAN}" >> $GITHUB_ENV
          fi

      - name: Build Go Binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o ${{ env.exe_name }} ./cmd/cli/main.go
          
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.exe_name }}
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}